# Your Solution

apiVersion: apps/v1
kind: Deployment  
metadata:
  name: book-catalog 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: book-catalog 
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog     
        image: sit722week7part2.azurecr.io/book-catalog:1  
        imagePullPolicy: Always  
        env:                
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: "postgresql://sit722_7_2_vish_user:A9Q2dhe4cnI2F1XHopJtn31rplXS4KAY@dpg-crem91qj1k6c73de9sh0-a.oregon-postgres.render.com/sit722_7_2_vish"
---
apiVersion: v1           
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer    
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000

apiVersion: apps/v1
kind: Deployment  
metadata:
  name: inventory-management 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: inventory-management 
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management    
        image: sit722week7part2.azurecr.io/inventory-management:1  
        imagePullPolicy: Always  
        env:                
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: "postgresql://sit722_7_2_vish_user:A9Q2dhe4cnI2F1XHopJtn31rplXS4KAY@dpg-crem91qj1k6c73de9sh0-a.oregon-postgres.render.com/sit722_7_2_vish"
---
apiVersion: v1           
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer    
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 8000

