# Your Solution
version: '3'
services: 
     
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
    - "4000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722_7_2_vish_user:A9Q2dhe4cnI2F1XHopJtn31rplXS4KAY@dpg-crem91qj1k6c73de9sh0-a.oregon-postgres.render.com/sit722_7_2_vish
    restart: "no"

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
    - "4001:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722_7_2_vish_user:A9Q2dhe4cnI2F1XHopJtn31rplXS4KAY@dpg-crem91qj1k6c73de9sh0-a.oregon-postgres.render.com/sit722_7_2_vish
    restart: "no"